### ISSUE TITLE
Vessels spawned in 1.16 don't appear in 1.18 after loading

### ISSUE THREAD

**Issue by EDToaster** [MuradAkh/LittleLogistics#101]

**Comment by EDToaster** [comment]
We're waiting on forge PR (MinecraftForge/MinecraftForge/pull/8412) to fix this. Seems to be related to `ChunkRenamesFix#renameField` and the fact that our entities don't have datafixers affixed to them.

Example fix:
https://github.com/ldtteam/minecolonies/blob/forge-dfu/src/main/java/com/minecolonies/coremod/MineColonies.java#L120

**Comment by EDToaster** [comment]
DFU the second has been closed, now tracking https://github.com/MinecraftForge/MinecraftForge/pull/8501

**Comment by MuradAkh** [comment]
closing as we won't be supporting 1.16->1.18 world upgrades, will consider in for future versions
