### ISSUE TITLE
[Minor bug] Guide has 'blogs' where it should say 'blocks'.

### ISSUE THREAD

**Issue by isaaclepes** [MuradAkh/LittleLogistics#111]
In-game manual entry for docks states:
"There are two dock blogs"

**Comment by EDToaster** [comment]
🤔 u rite. https://github.com/MuradAkh/LittleLogistics/blob/bfe370192f65f7d047218ac9b933b2d00b473ae8/src/main/resources/data/littlelogistics/patchouli_books/guide/en_us/entries/docks.json#L8

**Comment by EDToaster** [comment]
Fixed
