### ISSUE TITLE
Game crashes on startup

### ISSUE THREAD

**Issue by Minejerikisme** [MuradAkh/LittleLogistics#13]
Latest beta version on curseforge 
java8
Crash log
https://paste.ee/p/ak8AZ

**Comment by MuradAkh** [comment]
Are you trying to run a dedicated server or just a standalone client? Looks like I imported a client only class where I was not supposed to again

**Comment by MuradAkh** [comment]
Actually I see you are starting from multiMC. I am unable to reproduce this right now with the same forge version on multimc, will keep looking into it. Anything special about the setup?

**Comment by Minejerikisme** [comment]
Ill try using a brand new instance but there was nothing strange about the current instance I used multimc for the pre alpha versions to and they worked

**Comment by MuradAkh** [comment]
Could you also export the problematic instance and attach it to the issue. The class missing is a vanilla Minecraft class so it's hard for me to pinpoint the issue.

**Comment by EDToaster** [comment]
Tested with client-side `littlelogistics-mc1.16.5-v1.0.0-beta.2.jar` unable to reproduce crash:

- Forge 36.2.20
- 1.16.5
- Java 1.8

**Comment by MuradAkh** [comment]
@Minejerikisme can you confirm whether the issue is still present
