### ISSUE TITLE
Game crashes when loading world after swapping tug routes

### ISSUE THREAD

**Issue by EnderHawkeye** [MuradAkh/LittleLogistics#135]
I was messing around with the mod and few other mods in a creative world, and I swapped the tug route that was in an energy tug that had ~35 nodes with one that had 2 nodes, but when I did, it crashed my game. And every time I load the world, it crashes.

The error that I get on the minecraft launcher is an IndexOutOfBoundsExceptions: Index 7 out of bounds for length 1

[Here is the pastbin for the full crash log](https://pastebin.com/R19Jqa6A)

I have a sneaking suspicion that it may have been caused by it being in the middle of a route and I immediately swapped the item rather than pull the running route out of the tug then putting in the new one.

**Comment by EDToaster** [comment]
This is due to the fact that we don't set `nextStop` to 0 whenever the contents of the route changes.
Worlds that are broken by this bug cannot be loaded properly
