### ISSUE TITLE
[1.16] Ships not swimming, spinning in place

### ISSUE THREAD

**Issue by iarspider** [MuradAkh/LittleLogistics#153]
After update to 1.0.8, the tugboat doesn't follow route, but spins in place instead. Video demonstration: https://youtu.be/rdcK0-08FHA

**Comment by MuradAkh** [comment]
Hey, thanks for reporting!

Is this in a specific modpack? Are you using optifine or "small ships" mod?

Does replacing the vessels help?

I am not able to reproduce this in my 1.16 dev environment

**Comment by iarspider** [comment]
Yes, this is Enigmatica 6 (Expert). Yes, there is "Small Ships" mod in that modpack, but no optifine. 

I have tried downgrading to mod 1.0.5, but that didn't completely fix the problem - the area around the dock is, for some reason, not accessible for tugboat (neither with attached boats, nor alone).

**Comment by MuradAkh** [comment]
Couple things: 

Make sure there is no small ships boat nearby, they mess with pathfinding. 

Make sure there is a node inside the dock so that the tug actually sails though there

**Comment by iarspider** [comment]
How "nearby" is nearby? There was a small ship nearby (a couple of blocks behind the dock)...

**Comment by MuradAkh** [comment]
Yep, that's close enough. Just remove it. We've had 4 people report this already. They do something to water mob AIs when in range. Keep them few chunks away.

**Comment by iarspider** [comment]
Ah. That explains everything.

**Comment by MuradAkh** [comment]
@iarspider it appears that disabling `WaterMobFlee` in small ships config solves this

**Comment by MuradAkh** [comment]
https://github.com/EnigmaticaModpacks/Enigmatica6/pull/4561

Enigmatica PR to fix this
