### ISSUE TITLE
Possible Mod Incompatibility With Goblin Traders

### ISSUE THREAD

**Issue by BreadBox64** [MuradAkh/LittleLogistics#178]
[Crash Report](https://crashy.net/3ui0QPU4bTLA4JcE0M3D)
When I tried placing down a tug the game immediately crashed, but this didn't happen with other mod's vehicles
I looked at the crash report and it showed the stacktrace going through SyncedEntityData which was under a mod by MrCrayfish. Because Goblin Traders was the only mod by him I had installed that dealt with entities, I disabled it and is started working fine.
I don't know if this is misattribution or something, but I figured I might as well report it.

**Comment by MuradAkh** [comment]
I'm currently playing a world with both Little Logistics and goblin traders without any issues. Could you provide: 

1. the full crash log, not just the stack trace.
2. Lists of all the mods installed with versions. If you are using a modpack please specify
3. Are you playing on a dedicated server?

Also I'm not seeing any reference to Mr crayfish in the stack trace
