### ISSUE TITLE
Suggestion: Aquaculture 2 compat for auto-fishing barge

### ISSUE THREAD

**Issue by TheDarkPreacher** [MuradAkh/LittleLogistics#185]
Basically what the title says: When Aquaculture 2 is also present in a modpack, allow the auto-fishing barge to catch Aquaculture 2 fish.

Or, conversely, add in a configurable loot table for the auto-fishing barge so pack makers can add in other fish or treasures, besides just the vanilla fishing loot table.

**Comment by MuradAkh** [comment]
The loot table is already configurable, check the server config inside the save file. You want to change it to fishing instead of fishing/fish
