### ISSUE TITLE
[Suggestion] Let activator rail toggle chunk loader train car functionality

### ISSUE THREAD

**Issue by TheRealWormbo** [MuradAkh/LittleLogistics#187]
The idea is essentially the same as for hopper minecarts: If a hopper minecart movers over an activator rail, it changes state according to the activator rail's state. Currently the only option would be to manually remove that train car, to later place and manually link it again. That feels to me like it somewhat goes against the spirit of automation.

For the chunk loader train cart that could mean:
* If activator rail is turned off, the chunk loader train car works as usual.
* If the activator rail is turned on, the chunk loader train car stops loading chunks.

The reason for this suggestion is that there are performance benefits for not keeping chunks loaded when they aren't needed. For example, if you plan on leaving a server for some time and turn off the things your train is supposed to transport items/liquids from/to, there is absolutely no reason to still keep loading chunks for the train. It can stay docked (which already is a feature) and the chunk loader should be turned off until the train is needed in any way again.

I guess another, related idea would be to somehow also apply that idea to chunk loader barges, but I'm not sure how to translate it to that. Maybe as an effect of a barge dock, and only while the barge is docked and the dock receives a redstone signal or something like that?

**Comment by MuradAkh** [comment]
So essentially you are suggesting a way to: 
- Disable chunkloaders 
- do so automatically when trains are in storage

This is a solid suggestion, will look into it

**Comment by TheRealWormbo** [comment]
That's a good way to sum it up, although disabling chunk loading while in storage might not always be desireable, since holding the train in storage could be part of some kind of automation cycle that doesn't need the train doing its tour at all times, but could potentially still rely upon the chunk loading somehow.

**Comment by MuradAkh** [comment]
We got rid of chunkloaders in 1.19, so this issue is no longer applicable
