### ISSUE TITLE
Fluid hoppers dont take lava from Cauldrons

### ISSUE THREAD

**Issue by IvorAmlug** [MuradAkh/LittleLogistics#190]
So first of all awesome mod. Kinda gives me those Factorio train Track building fells but ive seem to have a tiny, Well Question here:
Now idk if this is just not implemented or a bug but my Fluid hoppes dont seem to intake from cauldrons above them.
That makes my plans for faster auto lava farming a bit useless ig.
So i rly wondered if its a thing and im Just to stupid or if thats something not yet implementet.

Forge 1.18.2 40.1.31
Little Logistics 1.18.2 1.2.5
Anyways not that big of a deal for know ill try to find another way to automaticly empty those cauldrons

**Comment by MuradAkh** [comment]
The reason for this is technical, vanilla claudrons aren't fluid holders in the same way as fluid tanks etc from other mods, and there isn't really a nice way to handle them with hoppers. It won't work unless forge changes claudrons to be tile entities with fluid handler capability
