### ISSUE TITLE
Tug stops when a hopper is placed on the tug dock (with coal in the hopper).

### ISSUE THREAD

**Issue by ncottrill** [MuradAkh/LittleLogistics#191]
The coal/burnables powered tug keeps getting stuck on the hopper that should feed it fuel. It is a normal Minecraft hopper. I have it positioned on a orange tug cube with hopper on top, as its posted in this video https://www.youtube.com/watch?v=4hI99VUqczw at about 13:32+ to the end. 

When I come back to check on the tug, after a time, it has halted (no steam coming out) at the tug dock. Internally, the GUI shows the tug in "play" mode.

As soon as I break the hopper and remove it, the tug starts moving again. This is an image of how the dock must be in order for the tug to continue its route. 

![image](https://user-images.githubusercontent.com/14022160/172914552-7d91821e-d8ef-4814-8a4c-f388937818bb.png)

Is there a reason why putting a hopper in the yellow square, filling it with coal, would make the tug stop?

**Comment by MuradAkh** [comment]
This was a bug in 1.2.4, 1.2.5 release fixes it
