### ISSUE TITLE
[1.16.5] Compat issue LL1.16.5-v1.0.8 + ED1.16.5-1.1.18

### ISSUE THREAD

**Issue by stfwi** [MuradAkh/LittleLogistics#197]
Hi Murad, an item handler insertion issue dropped into my Engineer's Decor mod, where we get a dupe of fuel when inserting from the Factory Hopper into the Steam Tug. I made a quick trace protocol for the insertion on the hopper side, and the return value of the tug item handler `insertItem()` method seems to accept the stacks (stack size 1), but there is more fuel in the tug after that.

The related issue is here: https://github.com/stfwi/engineers-decor/issues/221, I also pushed the data and relevant code passages there that we can synchronize better. 

Could you also take a look at the insertion matter? Would be great ))

Cheers, wile

**Comment by MuradAkh** [comment]
I'm guessing the issue is that factory hoppers use both the item handler capability and the IInventory? It's kind of a hack because vanilla hoppers don't work without IInventory, and it also lets me disable insertion when the tug isn't docked to avoid mixing stuff. 

Minecart uses only IInventory I think. It might be better not to expose the item handler capability of the tug at all, I can't recall if that's used somewhere else.

**Comment by stfwi** [comment]
Thanks for the quick response. Aye, I am using the forge `InvWrapper` if the entity is `IInventory`. Let me double check if using the explicit capability as preferred handler helps already. Cheers,-

**Comment by stfwi** [comment]
Quick info, explicitly preferring the item handler of the tug (from the hopper side) did the trick (I'll push the fix and inform the E6 devs). So your item handler is definitely ok for the fuel slot of the tug. 

It may be that there is something in the IInventory implementation of the tug fuel slot that may need attention. If you like (need something inserting via IInventory into the tug), I can recompile a dev version with detailed hopper tracing and attach it in the thread here. Cheers,-

**Comment by MuradAkh** [comment]
I would advise preferring IInventory instead, because that one is actually controlled to only insert when the tug is docked, otherwise the tug can pick up stuff from hoppers along the way

**Comment by stfwi** [comment]
Hi, sorry about the late response. I pushed the fix version already the same day, so the duping bug in E6 is mitigated. The bug was reproducible when inserting into the IInventory (via the Forge InvWrapper), and gone after using the item handler of the tug. I'll double check if docked/non-docked pickup is an issue. Cheers,-
