### ISSUE TITLE
Steam tug crashes game on place

### ISSUE THREAD

**Issue by Minejerikisme** [MuradAkh/LittleLogistics#2]
Optifine,little logistics,and jei multimc

Crash Log: https://pastebin.com/3YQBuwkk

**Comment by MuradAkh** [comment]
This looks like optifine comparability issue, I will look into it.

**Comment by MuradAkh** [comment]
I wasn't able to reproduce this issue locally. My guess based on logs is that this was a side effect of #3. Please let me know if the issue persists with the latest build.

**Comment by Minejerikisme** [comment]
It works perfectly now it doesn't crash anymore
