### ISSUE TITLE
[Compatibility/Botania, 1.18.2] Locomotives and trains cars have different "flight properties" from spectral rails

### ISSUE THREAD

**Issue by TheRealWormbo** [MuradAkh/LittleLogistics#202]
Okay, I admit this is a bit of a weird one. I was messing with Botania's Spectral Rail a bit to see if it could be useful for anything I'm currently working on and found that the steam locomotive jumps a lot further than any of the attached train cars. Additionally, it seems the more train cars you add, the lower the jump distance of the ones further back gets.
My test setup:
![2022-08-05_18 06 14](https://user-images.githubusercontent.com/7620864/183117776-f2c30fd3-e0ab-4ae6-b44d-80b19a0232ef.png)

As far as I can tell, the locomotive clears roughly the same distance as any vanilla minecart (almost regardless of propulsion method, including powered rails and furnace minecart), clearing a horizontal gap of about 10 blocks and snapping to the rail at the curve, while any train car, whether pulled by a locomotive or moved via powered rail, clears at most 6 blocks and snaps to the rail right at the edge of the gap. If the train is longer, train cars number 6+ won't even make the jump. As far as I can tell from observation, train cars have more "drag" while airborne, and this apparently also affects how far the spectral rail can launch them.
I'm not sure if this is worth fixing, but I though I'd at least document it here, in case anyone else attempts to jump their trains across ravines instead of building a bridge, or something.

**Comment by MuradAkh** [comment]
Don't think there's any easy solution to this and it's too minor for us to invest time into, sorry.
