### ISSUE TITLE
[Question/Request] AutoFishing storage

### ISSUE THREAD

**Issue by drakray** [MuradAkh/LittleLogistics#206]
Hi there, quick question: when auto-fishing, will the fishing barge use the chest barge storage to store fish/loot?
If not, would it be possible to do so?
Using mods that add fish/loot, it can potentially fill the fishing barge pretty quickly.
EDIT: I just saw that the fishing barge now have 27 slot instead of 9(like the Mischief video), might be enough?

**Comment by MuradAkh** [comment]
Yes we bumped it to 27 slots specifically for this reason
