### ISSUE TITLE
Recovery of broken tugs/barges

### ISSUE THREAD

**Issue by JonasDoe** [MuradAkh/LittleLogistics#211]
Hey, my biggest gripe with the mod is that there's always the danger to lose the stuff b/c the tug-barge chain breaks accidentally. Happened to me in E6E for I don't know what reason. It would be nice if
- broken tugs/barges keep don't despawn when broken and mb even keep their NBT/inventory.
- you could register your tug route (device) at a central monitoring block. This one could help you do locate your tug by displaying the latest known location (e.g. by coordinates).

Without it, it's a bit hard to put much trust into a tug setup, especially when it comes to item transportation.
Thanks for all your work!

**Comment by MuradAkh** [comment]
1.16 is no longer supported and lot of new big QOL additions are missing. 

In 1.19, you are able to register your tugs and find them using waypoints when holding the conductor's wrench.

**Comment by JonasDoe** [comment]
I understand. Great to her that you've already fixed that!
