### ISSUE TITLE
1.18.2 Chest Cart Duplication Bug

### ISSUE THREAD

**Issue by Laserlance141** [MuradAkh/LittleLogistics#214]
Basically the title, while I was playing around with the offloading mechanics, I found a fairly major duplication bug.
To set it up, all you need is a vanilla hopper with a docking rail above set to blue mode, along with a chest cart on top of it.
Fill the hopper with items, I've found that one in each slot works best, but a full hopper works as well.
Then put a stack of items greater than 1 into the chest cart above the hopper, and it nearly instantly fills to full. This is easiest to see with one item in each slot configuration of the hopper. Other configurations of the hopper don't fill as fast, requiring a few clicks by the user to duplicate up to the full stack, but still duplicate.
My current build is MC 1.18.2, Forge 40.1.92, and Little Logistics 1.2.6
Images for setup:
![image](https://user-images.githubusercontent.com/13091148/208989767-fc1a6457-5d96-48a5-85ac-8cb5a27eb91a.png)
![image](https://user-images.githubusercontent.com/13091148/208989898-43ff3fda-85d9-42c7-b1fc-e79e227fba6a.png)
![image](https://user-images.githubusercontent.com/13091148/208989961-64e801b2-1150-485e-b181-be8918288a7d.png)

**Comment by EDToaster** [comment]
Thanks for reporting this, we are aware of a similar/same duplication bug with the chest cart.

Tracking in addition to #216

**Comment by EDToaster** [comment]
This has been fixed a while ago, forgot to close the issue
