### ISSUE TITLE
Powered Tug Dock also stops refueling

### ISSUE THREAD

**Issue by BuggaNoia** [MuradAkh/LittleLogistics#215]
To stop the Steam Tug in place I use a Vessel Detector for powering the Tug Dock. Because of the Tug Dock has now redstone the Hopper above will not add fuel to the Tug.
Is there any way around, e.g. making the Hopper ignoring redstone?

**Comment by MuradAkh** [comment]
You can power the dock from below using a torch.

You also don't need to use any redstone to make the tug wait until loaded, the tug will automatically wait until all the items are loaded/unloaded from itself and the barges, provided the dock setup is correct. See 
http://littlelogistics.murad.dev for instructions
