### ISSUE TITLE
Feature Suggestion: Redstone powered dock gate

### ISSUE THREAD

**Issue by theboo** [MuradAkh/LittleLogistics#22]
Really loving this mod, super cute and unique!!!

One suggestion i had would be some sort of redstone powered gate to stop your boat at the docks. Currently it seems the only way to stop the boats is to try and catch the tug and remove the route card or let it run out of fuel. Would be nice to be able to stop it on command. Maybe a gate that stops it and makes the boat ignore the route card/guide rail until you un-power the gate?

**Comment by MuradAkh** [comment]
Yes we were thinking of forcing the docks to hold the vessel if there is a redstone signal, so this is coming soon probably!
