### ISSUE TITLE
[1.18.2] Train Car entry in book crashing game

### ISSUE THREAD

**Issue by DapperSpoder** [MuradAkh/LittleLogistics#230]
Whenever I open the Train Car entry in the Little Logistics Guide, the game crashes to desktop

Crashlog attached, I don't know what else to provide, but I can give more info if requested
[crash-2023-06-24_23.15.38-client.txt](https://github.com/MuradAkh/LittleLogistics/files/11856592/crash-2023-06-24_23.15.38-client.txt)

**Comment by MuradAkh** [comment]
Disable create compatibility in the common config file or downgrade create to 0.5
