### ISSUE TITLE
Log errors after placing Junction Rails (1.19.2)

### ISSUE THREAD

**Issue by ghost** [MuradAkh/LittleLogistics#231]
Minecraft Version: 1.19.2
Forge version: 43.2.10
Little Logistics version: v1.4.0

After placing junction rails in SP world, I'm getting these errors in latest log file: https://pastebin.com/j1M3wfQ5

**Comment by EDToaster** [comment]
Thanks for the bug report -- this is a known issue with how minecraft handles rail placement. It doesn't affect gameplay at all and just pollutes the log files.

**Comment by EDToaster** [comment]
Looks like forge added a hook here to allow us to fix this.
