### ISSUE TITLE
Solved question no need for help

### ISSUE THREAD

**Issue by traincrisis** [MuradAkh/LittleLogistics#235]
Solved

**Comment by MuradAkh** [comment]
Chunk loader cars were removed in 1.19, use the registration system instead. However you can still use /spawn to summon them

**Comment by traincrisis** [comment]
> Chunk loader cars were removed in 1.19, use the registration system instead. However you can still use /spawn to summon them

Add compatibility for Minecraft 1.19.3, 1.19.4, 1.20 and 1.20.1 please, also bring back the chunk loader train car
