### ISSUE TITLE
New versions

### ISSUE THREAD

**Issue by traincrisis** [MuradAkh/LittleLogistics#238]
Add compatibility for Minecraft 1.19.3, 1.19.4, 1.20 and 1.20.1 please, also bring back the chunk loader train car

**Comment by SigmaFlame** [comment]
1.19.3 is not played.
1.19.4 almost no mod are on it, except Rats that refuses to make their mod for 1.19.2.
1.20 is not played since there is the 1.20.1.

**Comment by MuradAkh** [comment]
Chunk loader car has been replaced by the registration system

We plan on eventually updated to 1.20.x
