### ISSUE TITLE
Steam Tug Fuel Multiplier.

### ISSUE THREAD

**Issue by iAskel** [MuradAkh/LittleLogistics#256]
Problem this old version is how i can increase fuel consumption in Steam Tug? If i try change config (i use Configured + Catalogue of MrCrayfish) and change the value to "999" or "9999" it doesn't run out of fuel. But one time i change 4 to 9999999 (i dont remember but is was max value) and fuel (64 pieces of coal) consume very fast. I need the fuel to run out quickly, but not in one minute, of course. In new version (1.20.1) its ok i can change value to 0.1 or 0.01 or something and its done. How i can change it in 1.16.5? And if im right correct new value apply only after fuel is burn in Tug?

**Comment by MuradAkh** [comment]
1.16.5 is no longer supported

**Comment by iAskel** [comment]
> 1.16.5 is no longer supported

You have a strange approach to mod development, it feels like I'm talking to ASUS tech support or something like that.
I found how fix that on 1.16.5 i found mod Configurable Furnace Burn Time and now i can change burn time in all furnace and it works with Steam Tug too.
https://www.curseforge.com/minecraft/mc-mods/configurable-furnace-burn-time
Thx for Serilum good modder or mod community i dont know.
