### ISSUE TITLE
2 issues Breaking any of the boats or linking two ships causes the game to crash

### ISSUE THREAD

**Issue by Minejerikisme** [MuradAkh/LittleLogistics#3]
Both with jei and little logistics (removed jei)

Breaking boat crash:https://pastebin.com/M4EC9BML

Linking boats crash:https://pastebin.com/HakRnuMn

**Comment by MuradAkh** [comment]
Looks like not every java installation comes with javafx then, I was relying on the pair definition from there. I will get rid of java fx dependency then. 

Thanks!

**Comment by MuradAkh** [comment]
Should be fixed in https://github.com/MuradAkh/LittleLogistics/releases/tag/pre-alpha-1.0.1
