### ISSUE TITLE
Item Names/Tooltips dont show up while in Tug GUIs

### ISSUE THREAD

**Issue by theboo** [MuradAkh/LittleLogistics#31]
As seen in the video below, while in either the steam or energy tug GUI, item tooltips/names dont show up when hovering over with a mouse.

https://gyazo.com/89b9bce45e79f58a2ddba2dde423a5c9

**Comment by EDToaster** [comment]
![image](https://user-images.githubusercontent.com/7676229/152595808-6df66c45-80ad-4e67-a8bf-2dbfbfecadf1.png)
