### ISSUE TITLE
[Feature Request] Support for modded fish from fishing barge

### ISSUE THREAD

**Issue by theboo** [MuradAkh/LittleLogistics#36]
Suggest changing from `FISHING_FISH` on the line below to just `FISHING` or `GAMEPLAY_FISHING` as it seems most mods (for example aquaculture 2) inject straight in to `minecraft:gameplay/fishing` vs `gameplay/fishing/fish`. Of course this would mean the player still has a chance at treasure if they dont win with the treasure chance modifier, but the chance of rolling the treasure table with an unenchanted rod is super low so i dont think it's a huge deal there. Also gives the chance at rolling the junk table haha so it balances out i think.
 https://github.com/MuradAkh/LittleLogistics/blob/14cd4cce1bd3a4316798756b1024c99d820fe245/src/main/java/dev/murad/shipping/entity/custom/barge/FishingBargeEntity.java#L145

on another note, do you guys have a discord server at all somewhere for the public?

**Comment by MuradAkh** [comment]
We don't have a discord sever yet! But we should probably make one. 

The general fishing one won't actually yield treasure because of the internal logic that requires the entity to be a fishing bob to grant treasure, the only issue with this would be lots of junk. We will consider it though!

**Comment by theboo** [comment]
Ah yeah, forgot about the bobber thing!

To be honest, it actually makes more sense to me that a fishing barge trolling with nets would pick up junk from the sea vs top water bobber fishing haha.

At the very least, thanks for the consideration!

**Comment by MuradAkh** [comment]
I will just make it configurable, then people can decide on deal with junk vs no mod fish

**Comment by MuradAkh** [comment]
About discord, https://discord.com/invite/T2F7f9wx

**Comment by EDToaster** [comment]
We're adding fishingLootTable config option to switch between different loot tables.
