### ISSUE TITLE
Vessel chain stays intact at any distance even when obstructed

### ISSUE THREAD

**Issue by Minejerikisme** [MuradAkh/LittleLogistics#5]
if one of the segments of gets stuck behind a block it stays connected and if you break the block it shoots toward the rest of the ship.

**Comment by MuradAkh** [comment]
Yeah I'm actually aware that it "works" this way, I am not actually sure what's the best way to handle those cases. I could break the chain if the distance is too long, but I also want it to be easy to construct tug trains/don't have them break often. Maybe a distance limit but on the larger end would be good.

**Comment by MuradAkh** [comment]
resolved in https://github.com/MuradAkh/LittleLogistics/releases/tag/v1.0.0-alpha.3
