### ISSUE TITLE
Optifine and Shader Compatibility

### ISSUE THREAD

**Issue by EDToaster** [MuradAkh/LittleLogistics#52]
Optifine and various shaders will not work when hovering the tug item. This causes terrible rendering glitches:

![image](https://user-images.githubusercontent.com/7676229/152721100-ce631547-3e83-4051-9223-c93807e37e63.png)

Tested with complimentary shaders and internal shaders

Low priority at the moment as Optifine is just a pain to deal with normally.

**Comment by EDToaster** [comment]
Can be fixed with custom render buffer, though it might be a bit slow https://gist.github.com/williewillus/30d7e3f775fe93c503bddf054ef3f93e

**Comment by MuradAkh** [comment]
Will be fixed in #54 provided no performance impact is detected
