### ISSUE TITLE
Changing tugs and barges hitbox height

### ISSUE THREAD

**Issue by luaxlab** [MuradAkh/LittleLogistics#56]
All tugs and barges seem to adopt the hitbox height of the default boat. This means that trying to interact with them from the side will quite often fail, due the hitbox not covering the entire model. I would suggest altering the hitboxes height to allow users to interact with entities in the way they are used to.

**Comment by MuradAkh** [comment]
I was able to improve this a bit, should be better in the next release. It won't be perfect since most of the hitbox needs to be underwater for navigation to work properly.

**Comment by MuradAkh** [comment]
![2022-02-08_23 19 28](https://user-images.githubusercontent.com/31002977/153121251-629a8869-71d8-4808-8f66-2eb8f4b7d9e4.png)
