### ISSUE TITLE
Feature suggestion: QOL tweaks

### ISSUE THREAD

**Issue by theboo** [MuradAkh/LittleLogistics#57]
Some QOL tweaks from the suggestions channel in discord:

- [x] Shears to cut chains
- [x] Recipe to clear route card
- [x] Recipe to copy route card on to another
- [ ] Bubble column avoidance(if possible)

**Comment by MuradAkh** [comment]
bubble column avoidance is possible but won't be done due to public opposition 
![image](https://user-images.githubusercontent.com/31002977/153527990-82234000-8fca-4a5a-a6ba-2ba5971c1b60.png)

**Comment by MuradAkh** [comment]
done
