### ISSUE TITLE
Request for version 1.18.1 with Create support?

### ISSUE THREAD

**Issue by PernDragon** [MuradAkh/LittleLogistics#63]
Just asking for a Version for 1.18.1, Thanks for making such a great idea.

**Comment by MuradAkh** [comment]
We already have an issue to look into a create contraption barge, would likely be an addon-mod if it ends up being possible. 

We haven't started on 1.18 port, we will likely start working on it in about two weeks, no ETA on completion.

**Comment by PernDragon** [comment]
Thank you, I will keep an eye open.
