### ISSUE TITLE
Dock only loads the first 6 slots of a chest barge

### ISSUE THREAD

**Issue by MrPeterman** [MuradAkh/LittleLogistics#79]
While a ship train is docked automatically (no redstone locking), every single chest barge only will be loaded with items in its first 6 slots, then the train undocks and travels on. Doesn't matter if  the items are unstackable or not. 
Paradoxically unloading items automatically will work with a full barge, just loading it fully doesn't work.
Is this intended behaviour or a bug?
Tested in v1.0.4.

**Comment by MuradAkh** [comment]
This is a bug, will try to reproduce and fix

**Comment by MuradAkh** [comment]
Bug reproduced, thanks a lot for reporting!
This was caused by default itemhandlers for mobs which have 6 slots for hands+armour. Since chest barge uses simple vanilla IInventory the default itemhandler managed to confuse the dock.
