### ISSUE TITLE
Feature suggestions/concepts on faster item transfer and inventory control

### ISSUE THREAD

**Issue by PrettyMuchTara** [MuradAkh/LittleLogistics#81]
As a concept to better transport bulks of a single item, you could add two new items:

1. Stack Hopper: a one slot, upgraded version of the vanilla hopper which transfers stacks of one items at a time to adjacent stack hoppers or barges, but at a lower speed than normal hoppers.

Calculation: Vanilla hoppers transfer 

> 1 item every 8 game ticks at a speed of 2.5 items/s, 

whereas the stack hopper could transfer 

> 16 items every 32 ticks at a speed of 10 items/s.

- To load a stack hopper fast, you need lots of hoppers pointing into it (4 hoppers concentrating into one stack hopper, then it will transfer into the next stack hopper, chest or barge).
- It can't pick up any items from a chest or item entities directly, items can only be inserted via hopper, stack hopper or other (modded) methods. 
- Not sure if barges should be able to be unloaded with stack hoppers or not. Maybe it shouldn't because a barge is a inventory and stack hoppers should only be loaded via hoppers, so there is the benefit of loading it quickly but unloading takes longer, so that would be balanced, idk.
- It can transfer into any inventory like chests or barges.
- Additonally, it has the same interaction with comparators like normal inventories, so you could use them in sorting system comparably to vanilla hopper sorting systems. 

2. Barrel Barge: a bit like a Storage drawer on water. It can hold 32 stacks of one item, can be loaded by hopper or stack hopper from above and lends a bit of its design from the vanilla barrel.

And one random suggestion: 

- Vessel Comparator: a block like the vessel detector, but it detects the fullness of the barge rather then the presence of a barge via redstone. It would still show 0 power if the barge is empty. 

Just as a note: your discord invitation from another issue expired. Can you please make a new one perhaps?

**Comment by MuradAkh** [comment]
There's a working link on curseforge

**Comment by PrettyMuchTara** [comment]
I'm blind apparently thank you

**Comment by MuradAkh** [comment]
I wanted some of your input on the rapid hopper:
1. How expensive should the rapid hopper be? We are thinking about using some redstone and gold in addition to the vanilla hopper, but not sure how much of each resource. (how many dust and how many bars for each rapid hopper)
2. How fast should it be? We can have it be 4x or 8x as fast as the vanilla hopper.

**Comment by MuradAkh** [comment]
rapid hopper has been added
